org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=false
org.gradle.caching=true
org.gradle.jvmargs=-Xmx3G -XX:+UseG1GC -Dfile.encoding=UTF-8


kineticcore_min_version=26.10.3
kineticcore_version_range=[26.10.3,)
mod_id=textstudio
mod_name=Text Studio
mod_license=LGPLv3
mod_version=26.9.20
use_auto_version=true
mod_group_id=dev.xyat.textstudio
mod_authors=XYAT
mod_description=Text rendering effects and chat presentation tools.

output_mods_dir=D:/NEWMODS
kineticcore_version=26.10.7

dev.kikugie.stonecutter.hard_mode=true
