org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=false
org.gradle.caching=true
org.gradle.jvmargs=-Xmx3G -XX:+UseG1GC -Dfile.encoding=UTF-8 -Dnet.minecraftforge.gradle.check.certs=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.2
forge_version_range=[47.4.2,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

kineticcore_version=26.9.25
kineticcore_version_range=[26.9.20,)
mod_id=textstudio
mod_name=Text Studio
mod_license=LGPLv3
mod_version=26.9.20
use_auto_version=true
mod_group_id=dev.xyat.textstudio
mod_authors=XYAT
mod_description=Text rendering effects and chat presentation tools.

output_mods_dir=D:/NEWMODS
