modLoader="javafml"
loaderVersion="${loader_version_range}"
license="LGPLv3"

[[mods]]
modId="textstudio"
version="${file.jarVersion}"
displayName="Text Studio"
authors="XYAT"
description='''
Text rendering effects and chat presentation tools.
'''

[[dependencies.textstudio]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.textstudio]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.textstudio]]
modId="kineticcore"
mandatory=true
versionRange="${kineticcore_version_range}"
ordering="AFTER"
side="BOTH"
